services:
  # 1. SQL Database (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: bdnv_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: shop_sql
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - bdnv_network

  # 2. NoSQL Database (MongoDB)
  mongodb:
    image: mongo:6.0
    container_name: bdnv_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bdnv_network

  # 3. Vector Database (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: bdnv_qdrant
    ports:
      - "6333:6333" # API Port
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - bdnv_network

volumes:
  pg_data:
  mongo_data:
  qdrant_data:

networks:
  bdnv_network:
    driver: bridge